/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import java.util.Map;
import model.CustomerManagement.CustomerProfile;
import model.OrderManagement.Order;
import model.OrderManagement.OrderItem;
import model.ProductManagement.Product;
import model.Supplier.Supplier;
import ui.Sales.PerformanceReportJPanel;
import ui.Sales.PriceAdjustJPanel;
import model.Supplier.Supplier;
import ui.Sales.MaxProfitMarginsJPanel;
import ui.Sales.browseProductsPanel;
import ui.Sales.manualSimulationJPanel;
import ui.Sales.runSimulation;

/**
 *
 * @author keerthichandrakanth
 */
public class MainJFrame extends javax.swing.JFrame {

     private PricingModel pricingModel;  // This will handle the data loading
     private Map<String, CustomerProfile> customers;
     private Map<String, Product> products;
     private Map<String, Order> orders;
   
      // Constructor accepts PricingModel to load data
    public MainJFrame(PricingModel pricingModel) {
        this.pricingModel = pricingModel;
        this.customers = pricingModel.getAllCustomers();
        this.products = pricingModel.getAllProducts();
        this.orders = pricingModel.getAllOrders();
        
         initComponents();
        // userWorkArea.setLayout(new CardLayout());
         this.setVisible(true);
  }


    // Method to load data and display it in the text areas
    // Method to load data and display it in the text areas
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        BtnBrowseProducts = new javax.swing.JButton();
        BtnAdjustPrices = new javax.swing.JButton();
        BtnDynamicSimulation = new javax.swing.JButton();
        BtnMaxProfitMargins = new javax.swing.JButton();
        BtnGenerateReport1 = new javax.swing.JButton();
        BtnManualSimulation1 = new javax.swing.JButton();
        userWorkArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnBrowseProducts.setText("Price Performance");
        BtnBrowseProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBrowseProductsActionPerformed(evt);
            }
        });

        BtnAdjustPrices.setText("Adjust Prices");
        BtnAdjustPrices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdjustPricesActionPerformed(evt);
            }
        });

        BtnDynamicSimulation.setText("Dynamic Simulation");
        BtnDynamicSimulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDynamicSimulationActionPerformed(evt);
            }
        });

        BtnMaxProfitMargins.setText("Max Profit Margins");
        BtnMaxProfitMargins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMaxProfitMarginsActionPerformed(evt);
            }
        });

        BtnGenerateReport1.setText("Generate Report");
        BtnGenerateReport1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGenerateReport1ActionPerformed(evt);
            }
        });

        BtnManualSimulation1.setText("Manual Simulation");
        BtnManualSimulation1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnManualSimulation1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addComponent(BtnManualSimulation1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(BtnAdjustPrices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnBrowseProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(BtnMaxProfitMargins)
                                .addComponent(BtnGenerateReport1))
                            .addComponent(BtnDynamicSimulation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        controlPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BtnAdjustPrices, BtnBrowseProducts, BtnDynamicSimulation, BtnGenerateReport1, BtnManualSimulation1, BtnMaxProfitMargins});

        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(BtnBrowseProducts)
                .addGap(18, 18, 18)
                .addComponent(BtnAdjustPrices)
                .addGap(18, 18, 18)
                .addComponent(BtnDynamicSimulation)
                .addGap(22, 22, 22)
                .addComponent(BtnManualSimulation1)
                .addGap(18, 18, 18)
                .addComponent(BtnMaxProfitMargins)
                .addGap(18, 18, 18)
                .addComponent(BtnGenerateReport1)
                .addContainerGap(530, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(controlPanel);

        userWorkArea.setPreferredSize(new java.awt.Dimension(1500, 800));
        userWorkArea.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(userWorkArea);
        userWorkArea.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1636, Short.MAX_VALUE)
                .addContainerGap(329, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Map<String, Integer> initialPrices = new HashMap<>();

    private void BtnAdjustPricesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdjustPricesActionPerformed
        PriceAdjustJPanel pajp = new PriceAdjustJPanel(userWorkArea, products, initialPrices);
        userWorkArea.add("PriceAdjustJPanel", pajp);
        CardLayout layout = (CardLayout) userWorkArea.getLayout();
        layout.next(userWorkArea);
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAdjustPricesActionPerformed

    private void BtnBrowseProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBrowseProductsActionPerformed
        // TODO add your handling code here:
        browseProductsPanel bpjp = new browseProductsPanel(products,orders);
        userWorkArea.add("browseProductsPanel",bpjp);
        CardLayout layout = (CardLayout)userWorkArea.getLayout();
        layout.next(userWorkArea);
    }//GEN-LAST:event_BtnBrowseProductsActionPerformed

    private void BtnMaxProfitMarginsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMaxProfitMarginsActionPerformed
        MaxProfitMarginsJPanel mpmjp = new MaxProfitMarginsJPanel(orders);  
        userWorkArea.add("MaxProfitMarginJPanel", mpmjp);
        CardLayout layout = (CardLayout) userWorkArea.getLayout();
        layout.next(userWorkArea);
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnMaxProfitMarginsActionPerformed

    private void BtnDynamicSimulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDynamicSimulationActionPerformed
        // TODO add your handling code here:
        runSimulation rsjp = new runSimulation(orders);
        userWorkArea.add("runSimulation", rsjp);
        CardLayout layout = (CardLayout) userWorkArea.getLayout();
        layout.next(userWorkArea);
    }//GEN-LAST:event_BtnDynamicSimulationActionPerformed

    private void BtnGenerateReport1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGenerateReport1ActionPerformed
       
        PerformanceReportJPanel prjp = new PerformanceReportJPanel(userWorkArea, products, initialPrices);
        userWorkArea.add("PerformanceReportJPanel", prjp);
        CardLayout layout = (CardLayout) userWorkArea.getLayout();
        layout.next(userWorkArea);
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnGenerateReport1ActionPerformed

    private void BtnManualSimulation1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnManualSimulation1ActionPerformed
       
        manualSimulationJPanel msjp = new manualSimulationJPanel(orders);
        userWorkArea.add("manualSimulationJPanel", msjp);
        CardLayout layout = (CardLayout) userWorkArea.getLayout();
        layout.next(userWorkArea);
// TODO add your handling code here:
    }//GEN-LAST:event_BtnManualSimulation1ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdjustPrices;
    private javax.swing.JButton BtnBrowseProducts;
    private javax.swing.JButton BtnDynamicSimulation;
    private javax.swing.JButton BtnGenerateReport1;
    private javax.swing.JButton BtnManualSimulation1;
    private javax.swing.JButton BtnMaxProfitMargins;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel userWorkArea;
    // End of variables declaration//GEN-END:variables
}
