/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Sales;

import java.util.Map;
import javax.swing.table.DefaultTableModel;
import model.OrderManagement.Order;
import model.OrderManagement.OrderItem;
import model.ProductManagement.Product;

/**
 *
 * @author keerthichandrakanth
 */
public class browseProductsPanel extends javax.swing.JPanel {

     private Map<String, Product> products ;
     private Map<String, Order> orders;
     /**
     * Creates new form browseProductsPanel
     * @param products
     */
    public browseProductsPanel(Map<String,Product> products, Map<String, Order> orders) {
         this.products = products;
         this.orders = orders;
        initComponents();
        
        refreshTable();
         
    }
    
    
         public void refreshTable() {

        DefaultTableModel model = (DefaultTableModel) tblProductPerformance.getModel();
        model.setRowCount(0);
          for (Order order : orders.values()) {
            for (OrderItem item : order.getOrderitems()) {
                Object[] row = new Object[7];
                
                row[0] = item.getSelectedProduct().getName();
                row[1] = item.getSelectedProduct().getCeilingPrice();
                row[2] = item.getSelectedProduct().getTargetPrice();
                row[3] = item.getActualPrice();
                row[4] = item.calculatePricePerformanceforSingleQuantity();
                row[5] = item.calculatePricePerformance();
                row[6] = item.calculatePricePerformancePercentage();
                
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductPerformance = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblProductPricePerformance = new javax.swing.JLabel();

        tblProductPerformance.setAutoCreateRowSorter(true);
        tblProductPerformance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ProductName", "CeilingPrice", "TargetPrice", "Actual", "Price Performance per Unit", "Total Price Performance	", "Performace & Per Unit"
            }
        ));
        tblProductPerformance.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblProductPerformance.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblProductPerformance.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tblProductPerformanceComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(tblProductPerformance);

        lblProductPricePerformance.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblProductPricePerformance.setText("Product Price Performance");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProductPricePerformance)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProductPricePerformance)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1219, Short.MAX_VALUE)
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(490, 490, 490))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(167, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblProductPerformanceComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tblProductPerformanceComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_tblProductPerformanceComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblProductPricePerformance;
    private javax.swing.JTable tblProductPerformance;
    // End of variables declaration//GEN-END:variables
}
