/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Sales;

import java.util.Map;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.ProductManagement.Product;

/**
 *
 * @author AnjanaSruthiR
 */
public class PerformanceReportJPanel extends javax.swing.JPanel {

    private JPanel UserWorkArea;
     public Map<String, Product> products ;
     public Map<String, Integer> initialPrices;
    /**
     * Creates new form PerformanceReportJPanel
     */
    public PerformanceReportJPanel(JPanel UserWorkArea, Map<String, Product> products, Map<String, Integer> initialPrices) {
        initComponents();
        this.UserWorkArea = UserWorkArea;
        this.products = products;
        this.initialPrices = initialPrices;
        
        populateReportTable();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrollPane = new javax.swing.JScrollPane();
        TblReport = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        TblReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Product Name", "Initial Target Price", "Adjusted Target Price", "Actual Revenue", "Above Target", "Below Target"
            }
        ));
        ScrollPane.setViewportView(TblReport);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Product Performance Report");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void populateReportTable() {
    DefaultTableModel model = (DefaultTableModel) TblReport.getModel();
    model.setRowCount(0); 

    for (Map.Entry<String, Product> entry : products.entrySet()) {
        String productName = entry.getKey();
        Product product = entry.getValue();
        Object[] row = new Object[6];
        row[0] = productName;
        row[1] = initialPrices.get(productName);
        row[2] = product.getTargetPrice();
        row[3] = product.getActualSales() * product.getTargetPrice(); 
        row[4] = product.getNumberOfProductSalesAboveTarget(); 
        row[5] = product.getNumberOfProductSalesBelowTarget(); 

        model.addRow(row); 
    }
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JTable TblReport;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
